#!/usr/bin/env python3
"""
compute_stage2_switch_blends.py — emit the P2 / P3 data presets for the stage2
mid-run blend switches (2026-07 plan: Nemotron-3-style curriculum).

Reads token counts of every packed constituent directly from bin_bytes/4
(int32; packed bins are exactly seq-length 4096, <1% EOD pad), splits each
category's target share across its members proportionally to measured size,
and writes flat Megatron data YAMLs.

Categories and target shares (cluster-total, decided 2026-07-29):
  P2 (switch at ckpt 14,000, stable remainder):
      specialized 15  math 20  code 13  cc_actual 22.5  cc_qa 23  korean 4  fw2hq 2.5
  P3 (switch at ckpt 24,000, ~decay onset):
      specialized 35  math 18  code 10  cc_actual 6     cc_qa 21  korean 6  fw2hq 4

"specialized" = all 15 Nemotron-Pretraining-Specialized v1/v1.1/v1.2 subsets
(user approved DeepSeek-v3-derived subsets; wiki_rewrite / scientific_coding
are CC BY-SA — included per 2026-07-29 decision).

Usage:
  python tools/compute_stage2_switch_blends.py                  # print tables only
  python tools/compute_stage2_switch_blends.py --write          # also write both YAMLs
  python tools/compute_stage2_switch_blends.py --allow-missing  # while packing is in flight
"""
import argparse
import os

PACKED = "/home/work/Datasets/LL_preprocessed/v5/stage2_packed"

# category -> [relative prefix under PACKED]
CATEGORIES = {
    "korean":    ["korean_web"],
    "fw2hq":     ["fineweb2hq"],
    "math":      ["math"],
    "code":      ["code/code_review", "code/question_answering", "code/rewriting",
                  "code/student_teacher", "code/transpilation"],
    "cc_actual": ["nemotron_cc_hq/actual"],
    "cc_qa":     ["nemotron_cc_hq/qa_pairs"],
    "specialized": [
        "specialized/v1.1/code_concepts", "specialized/v1.1/economics",
        "specialized/v1.1/formal_logic", "specialized/v1.1/multiple_choice",
        "specialized/v1.1/unconditional_algorithmic",
        "specialized/v1/infinibyte_reasoning", "specialized/v1/math_textbooks",
        "specialized/v1/rqa", "specialized/v1/stem_sft",
        "specialized/v1/scientific_coding", "specialized/v1/wiki_rewrite",
        "specialized/v1.2/fact_seeking", "specialized/v1.2/generative",
        "specialized/v1.2/moral_scenarios", "specialized/v1.2/multiple_choice",
    ],
}

PLANS = {
    "p2": {"specialized": 15.0, "math": 20.0, "code": 13.0, "cc_actual": 22.5,
           "cc_qa": 23.0, "korean": 4.0, "fw2hq": 2.5},
    "p3": {"specialized": 35.0, "math": 18.0, "code": 10.0, "cc_actual": 6.0,
           "cc_qa": 21.0, "korean": 6.0, "fw2hq": 4.0},
}

HEADER = """\
# Stage 2 {name} blend — mid-run switch preset (generated by
# tools/compute_stage2_switch_blends.py, 2026-07 Nemotron-3-style curriculum).
#
# {desc}
# Same packed tree rules as stage2_v5_blend_packed.yaml: baseline_48L only,
# --seq-length 4096, EOD id 0 pad, weights are honored by Megatron (normalized).
# Do NOT edit weights by hand — regenerate with the tool so the epoch table in
# the run log stays truthful.
"""


def tokens_of(rel):
    p = f"{PACKED}/{rel}/data_text_document.bin"
    return os.path.getsize(p) // 4 if os.path.exists(p) else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write both YAMLs under configs/data/")
    ap.add_argument("--allow-missing", action="store_true")
    args = ap.parse_args()

    toks, missing = {}, []
    for cat, rels in CATEGORIES.items():
        for rel in rels:
            t = tokens_of(rel)
            if t is None:
                missing.append(rel)
            else:
                toks[rel] = t
    if missing:
        print(f"MISSING {len(missing)} packed subsets:")
        for m in missing:
            print(f"  - {m}")
        if not args.allow_missing:
            raise SystemExit("refusing to emit weights from an incomplete tree "
                             "(use --allow-missing to preview)")

    cat_tot = {c: sum(toks.get(r, 0) for r in rels) for c, rels in CATEGORIES.items()}
    total = sum(cat_tot.values())
    print(f"packed corpus total = {total/1e9:.1f}B tokens "
          f"(specialized {cat_tot['specialized']/1e9:.1f}B)\n")

    for name, plan in PLANS.items():
        assert abs(sum(plan.values()) - 100.0) < 1e-6
        print(f"=== {name.upper()} ===  {'category':12s} {'share':>6s} {'corpus':>9s}")
        pairs = []
        for cat, rels in CATEGORIES.items():
            share = plan[cat]
            print(f"{'':24s}{cat:12s} {share:5.1f}% {cat_tot[cat]/1e9:8.1f}B")
            for rel in rels:
                if rel in toks and cat_tot[cat] > 0:
                    w = share / 100.0 * toks[rel] / cat_tot[cat]
                    pairs.append((w, rel))
        data_path = " ".join(f"{w:.6f} {PACKED}/{r}/data_text_document" for w, r in pairs)
        if args.write:
            here = os.path.dirname(os.path.abspath(__file__))
            out = os.path.join(here, "..", "configs", "data",
                               f"stage2_v5_blend_packed_{name}.yaml")
            desc = ("P2: stable-phase remainder after ckpt 14,000 — specialized in at 15%."
                    if name == "p2" else
                    "P3: decay-window blend after ckpt 24,000 — specialized 35%, quality-max.")
            with open(os.path.normpath(out), "w") as f:
                f.write(HEADER.format(name=name.upper(), desc=desc))
                f.write(f'data-path: "{data_path}"\n')
                f.write('split: "99,1,0"\ndataset: MMAP\nnum-workers: 16\n')
            print(f"  -> wrote {os.path.normpath(out)}")
        print()


if __name__ == "__main__":
    main()
