#!/usr/bin/env python3
"""
compute_blend_weights.py — derive explicit Megatron blend weights that cap CC-HQ's
share and redistribute the remainder across math/code/korean by their natural
(size-proportional) ratio.

Why: the weight-less stage2_v5_blend.yaml auto-mixes by .idx size, so CC-HQ
(≈60% of the corpus) dominates. Under a small training budget (e.g. 0.5–0.7T)
the curated math/code/korean sets barely get trained. Capping CC-HQ and
redistributing its excess *proportionally* keeps each non-CC-HQ category's
internal mix untouched and gives all three the SAME epoch count.

Token counts are read instantly as bin_bytes / 4 (int32; verified bin = sum_lens*4
by Phase B). No GPU / no full IndexedDataset load.

Usage:
  python compute_blend_weights.py --cap-cchq 40 --budget-t 0.6
  python compute_blend_weights.py --cap-cchq 40 --write ../configs/data/stage2_v5_blend_cc40.yaml
"""
import argparse
import os

V5 = "/home/work/Datasets/LL_preprocessed/v5/stage2"

# (category, prefix-relative-to-V5) in the canonical blend order
DATASETS = [
    ("Korean",  "korean_web"),
    ("FineWeb", "fineweb2hq"),
    ("Math",    "math"),
    ("Code",    "code/code_review"),
    ("Code",    "code/question_answering"),
    ("Code",    "code/rewriting"),
    ("Code",    "code/student_teacher"),
    ("Code",    "code/transpilation"),
    ("CC-HQ",   "nemotron_cc_hq/actual"),
    ("CC-HQ",   "nemotron_cc_hq/qa_pairs"),
]
# Non-CC-HQ categories that receive CC-HQ's redistributed share (by natural ratio)
OTHERS = ["Code", "Math", "Korean", "FineWeb"]


def tokens_of(rel):
    binp = f"{V5}/{rel}/data_text_document.bin"
    if not os.path.exists(binp):
        raise FileNotFoundError(binp)
    return os.path.getsize(binp) // 4  # int32 → 4 bytes/token


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cap-cchq", type=float, default=40.0, help="CC-HQ target share in %% (default 40)")
    ap.add_argument("--budget-t", type=float, default=0.6, help="training budget in T tokens (for epoch table)")
    ap.add_argument("--write", help="write a stage2 data YAML to this path")
    args = ap.parse_args()

    avail = {rel: tokens_of(rel) for _, rel in DATASETS}
    cat_of = {rel: c for c, rel in DATASETS}
    cats = {}
    for _, rel in DATASETS:
        cats[cat_of[rel]] = cats.get(cat_of[rel], 0) + avail[rel]
    total = sum(avail.values())

    others = [c for c in OTHERS if c in cats]
    cat_order = ["CC-HQ"] + others
    others_tot = sum(cats[c] for c in others)
    rem = 100.0 - args.cap_cchq
    catshare = {"CC-HQ": args.cap_cchq}
    for c in others:
        catshare[c] = rem * cats[c] / others_tot

    # per-prefix weight = category share × (prefix tokens / category tokens)
    weights = {rel: catshare[cat_of[rel]] / 100.0 * (avail[rel] / cats[cat_of[rel]])
               for _, rel in DATASETS}

    B = args.budget_t * 1e12
    print(f"corpus total {total/1e9:.1f}B tokens | CC-HQ cap {args.cap_cchq:.0f}% | budget {args.budget_t*1000:.0f}B\n")
    print(f"  {'category':8s} {'share':>6s} {'tokens@budget':>14s} {'epochs':>7s}")
    for c in cat_order:
        toks = catshare[c] / 100 * B
        ep = toks / cats[c]
        warn = "  <-- repeats >1ep" if ep > 1.0 else ""
        print(f"  {c:8s} {catshare[c]:5.1f}% {toks/1e9:13.1f}B {ep:6.2f}x{warn}")

    data_path = " ".join(f"{weights[rel]:.4f} {V5}/{rel}/data_text_document" for _, rel in DATASETS)
    print("\ndata-path:\n  \"" + data_path + "\"")

    if args.write:
        lines = [
            "# Stage 2 v5 blend — CC-HQ capped, others redistributed by natural ratio.",
            f"# Generated by tools/compute_blend_weights.py --cap-cchq {args.cap_cchq:.0f}",
            "#",
            "# Explicit weights decouple sampling from .idx size (vs weight-less",
            "# stage2_v5_blend.yaml where CC-HQ = 59.9%). CC-HQ's excess share is",
            "# redistributed across math/code/korean by their natural size ratio, so",
            "# each non-CC-HQ category keeps its internal mix and all share one epoch rate.",
            "#",
            f"# Category shares (cap {args.cap_cchq:.0f}%):",
        ]
        for c in cat_order:
            toks = catshare[c] / 100 * B
            lines.append(f"#   {c:7s} {catshare[c]:5.1f}%   {toks/1e9:6.1f}B @ {args.budget_t*1000:.0f}B budget   {toks/cats[c]:.2f} epoch")
        lines += [
            "#",
            "# Weights are relative (Megatron normalizes). To change the cap/budget,",
            "# re-run tools/compute_blend_weights.py.",
            "",
            f'data-path: "{data_path}"',
            'split: "99,1,0"',
            "dataset: MMAP",
            "num-workers: 8",
            "",
        ]
        with open(args.write, "w") as f:
            f.write("\n".join(lines))
        print(f"\nwrote {args.write}")


if __name__ == "__main__":
    main()
